#! /bin/bash
avr-objcopy -I ihex -O binary $1 TEMP.BIN
./theGreatPrepender

rm ./TEMP.BIN

echo "
 verbose
 open ftp.site.com
 user ftpuser password
 delete FIRMWARE.BIN
 binary
 put FIRMWARE.BIN
 bye
" | ftp -n -p > ./ftplogs/ftp_$$.log
