#!/usr/bin/env python3
import os

inputFile = open('IN.BIN', 'rb')
outputFile = open('OUT.BIN', 'wb')

data = inputFile.read()

def fletcher_16(data, modulus=255):
    """Calculate the Fletcher-16 checksum of *data*, default modulus 255."""
    numbers = data
    a = b = 0
    for number in numbers:
        #print(number)
        a = (a + number) % modulus
        b = (a + b) % modulus
    print(a)
    print(b)
    outputFile.write(a.to_bytes(2, byteorder='big', signed=True))
    outputFile.write(b.to_bytes(2, byteorder='big', signed=True))
    return hex((a << 8) | b)[2:].upper().zfill(4)


outputFile.write(os.path.getsize('IN.BIN').to_bytes(2, byteorder='big', signed=True))
fletcher_16(data[:])
print(os.path.getsize('IN.BIN'))

outputFile.write(data)
outputFile.close()
inputFile.close()
