#!/usr/bin/env python3
import os

inputFile = open('TEMP.BIN', 'rb')
outputFile = open('FIRMWARE.BIN', 'wb')

data = inputFile.read()

def fletcher_16(data, modulus=255):
    """Calculate the Fletcher-16 checksum of *data*, default modulus 255."""
    numbers = data
    a = b = 0
    for number in numbers:
        a = (a + number) % modulus
        b = (a + b) % modulus
    outputFile.write(a.to_bytes(1, byteorder='big', signed=False))
    outputFile.write(b.to_bytes(1, byteorder='big', signed=False))


outputFile.write(os.path.getsize('TEMP.BIN').to_bytes(2, byteorder='big', signed=False))
fletcher_16(data[:])
print(os.path.getsize('TEMP.BIN'))

outputFile.write(data)
outputFile.close()
inputFile.close()
